CREATE TABLE snapshot (
    ai INT PRIMARY KEY,
    invoice_number BIGINT NULL,
    position INT NULL,
    invoice_date TIMESTAMP NULL,
    paid_date TIMESTAMP NULL,
    month_period INT NULL,
    dpp DECIMAL(15, 2) NULL,
    new_sub DECIMAL(15, 2) NULL,
    modal DECIMAL(15, 2) DEFAULT 0,
    description TEXT NULL,
    customer_service_id INT NULL,
    customer_id VARCHAR(20) NULL,
    customer_company VARCHAR(255) NULL,
    service_group_id VARCHAR(20) NULL,
    service_id VARCHAR(20) NULL,
    service_name VARCHAR(255) NULL,
    sales_id VARCHAR(20) NULL,
    manager_sales_id VARCHAR(20) NULL,
    is_new BOOLEAN NOT NULL DEFAULT false,
    is_upgrade BOOLEAN NOT NULL DEFAULT false,
    is_termin BOOLEAN NOT NULL DEFAULT false,
    implementator_id VARCHAR(20) NULL,
    sales_commission DECIMAL(15, 2) NULL,
    sales_commission_percentage DECIMAL(5, 2) NULL,
    referral_id VARCHAR(20) NULL,
    type ENUM('internal', 'resell') NOT NULL,
    type_sub ENUM('flex', 'annual_yearly', 'annual_monthly') NULL,
    cross_sell_count INT NOT NULL DEFAULT 0,
    upgrade_count INT NOT NULL DEFAULT 0
    is_adjustment BOOLEAN NOT NULL DEFAULT false,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
);

CREATE TABLE adjustment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ai INT NOT NULL,
    employee_id VARCHAR(20) NOT NULL,
    approved_id VARCHAR(20) NULL,
    old_value JSON NULL,
    new_value JSON NULL,
    note TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    action ENUM('insert', 'update', 'delete') NOT NULL,
    status ENUM('pending', 'accept', 'decline') NOT NULL DEFAULT 'pending'
);

CREATE TABLE employee (
    id INT PRIMARY KEY,
    employee_id VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    photo_profile VARCHAR(255) NOT NULL,
    job_position VARCHAR(255) NOT NULL,
    organization_name VARCHAR(255) NOT NULL,
    job_level VARCHAR(50) NOT NULL,
    branch VARCHAR(255) NOT NULL,
    manager_id INT NULL,
    has_dashboard BOOLEAN NOT NULL DEFAULT false
);
